### ISSUE TITLE
plurals ("curies" vs "h:link")

### ISSUE THREAD

**Issue by randallsquared** [inadarei/hyper#9]
In some places (maybe only curies and profiles), we use a plural, and in others a singular, even where both of the places support a multiple of the described definition.

Should we normalize all of these to singular or plural?

**Comment by inadarei** [comment]
Well, profiles are gone, so one less to worry about :)

Candidly, I am largely indifferent to this. I feel like the elements of the core vocabulary MUST be consistent (i.e. all names under `h:` prefix) but that's where my care for consistency stops.

The `curies` is part of the description of `h:head` - one level detached from the core vocabulary. It doesn't carry "h:" prefix and is just part of what I see as "local" spec. I feel "curies" makes it more obvious that the value of it should be an array, but that's also not that important.

If you feel very strongly about it  - we can change, my feeling was just:

1. It is more natural to write and pronounce.
2. We do sacrifice "more natural" for the sake of consistency, in the core vocabulary, but since this was one level detached - I didn't care.

**Comment by randallsquared** [comment]
I agree that `curies` is better.  I was initially leaning toward using `h:links`, but that immediately brings up `rel`, which is so common that using it instead of `rels` would be a very common mistake, were we to insist on `rels`.   So, good talk.  Closing. :)
